export const data = {
    cars:[
    {
        img: "https://th.bing.com/th/id/OIP.GSab87SYWZeVA4zj5Om65wHaEK?pid=ImgDet&rs=1",
        name:'Toyota RAV4',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Hybrid',
        mileage:'6.1',
        rent_price:'440',
        page:1,
    },
    {
        img:"https://th.bing.com/th/id/OIP.khW3FsQQ-vVq6zEyAhN5ygHaE8?pid=ImgDet&rs=1",
        name:'BMW 3 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'8.2',
        rent_price:'350',
        page:1,
    },
    {
        img:'https://media.autoexpress.co.uk/image/private/s--cPAkU3m9--/v1563182810/autoexpress/2019/04/01_53.jpg',
        name:'VW T-Cross',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'5.3',
        rent_price:'400',
        page:1,
    },
    {
        img:'https://cdn.motor1.com/images/mgl/lNnnl/s1/cadillac-escalade-sport-edition.jpg',
        name:'Cadillac Escalade',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.7',
        rent_price:'620',
        page:1,
    },
    {
        img:'https://th.bing.com/th/id/OIP.cAzshZwI01cwuyX2YgwwtAHaE8?pid=ImgDet&rs=1',
        name:'BMW 4 Series GTI',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.6',
        rent_price:'530',
        page:1,
    },
    {
        img:'https://cdn.bmwblog.com/wp-content/uploads/2017/01/2017-BMW-4-Series-M-Sport-Coupe-25.jpg',
        name:'BMW 4 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.2',
        rent_price:'490',
        page:1,
    },
    {
        img: "https://th.bing.com/th/id/OIP.GSab87SYWZeVA4zj5Om65wHaEK?pid=ImgDet&rs=1",
        name:'Toyota RAV4',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Hybrid',
        mileage:'6.1',
        rent_price:'440',
        page:2,
    },
    {
        img:"https://th.bing.com/th/id/OIP.khW3FsQQ-vVq6zEyAhN5ygHaE8?pid=ImgDet&rs=1",
        name:'BMW 3 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'8.2',
        rent_price:'350',
        page:2,
    },
    {
        img:'https://media.autoexpress.co.uk/image/private/s--cPAkU3m9--/v1563182810/autoexpress/2019/04/01_53.jpg',
        name:'VW T-Cross',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'5.3',
        rent_price:'400',
        page:2,
    },
    {
        img:'https://cdn.motor1.com/images/mgl/lNnnl/s1/cadillac-escalade-sport-edition.jpg',
        name:'Cadillac Escalade',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.7',
        rent_price:'620',
        page:2,
    },
    {
        img:'https://th.bing.com/th/id/OIP.cAzshZwI01cwuyX2YgwwtAHaE8?pid=ImgDet&rs=1',
        name:'BMW 4 Series GTI',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.6',
        rent_price:'530',
        page:2,
    },
    {
        img:'https://cdn.bmwblog.com/wp-content/uploads/2017/01/2017-BMW-4-Series-M-Sport-Coupe-25.jpg',
        name:'BMW 4 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.2',
        rent_price:'490',
        page:2,
    },
    {
        img: "https://th.bing.com/th/id/OIP.GSab87SYWZeVA4zj5Om65wHaEK?pid=ImgDet&rs=1",
        name:'Toyota RAV4',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Hybrid',
        mileage:'6.1',
        rent_price:'440',
        page:3,
    },
    {
        img:"https://th.bing.com/th/id/OIP.khW3FsQQ-vVq6zEyAhN5ygHaE8?pid=ImgDet&rs=1",
        name:'BMW 3 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'8.2',
        rent_price:'350',
        page:3,
    },
    {
        img:'https://media.autoexpress.co.uk/image/private/s--cPAkU3m9--/v1563182810/autoexpress/2019/04/01_53.jpg',
        name:'VW T-Cross',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'5.3',
        rent_price:'400',
        page:3,
    },
    {
        img:'https://cdn.motor1.com/images/mgl/lNnnl/s1/cadillac-escalade-sport-edition.jpg',
        name:'Cadillac Escalade',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.7',
        rent_price:'620',
        page:3,
    },
    {
        img:'https://th.bing.com/th/id/OIP.cAzshZwI01cwuyX2YgwwtAHaE8?pid=ImgDet&rs=1',
        name:'BMW 4 Series GTI',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.6',
        rent_price:'530',
        page:3,
    },
    {
        img:'https://cdn.bmwblog.com/wp-content/uploads/2017/01/2017-BMW-4-Series-M-Sport-Coupe-25.jpg',
        name:'BMW 4 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.2',
        rent_price:'490',
        page:3,
    },
    {
        img: "https://th.bing.com/th/id/OIP.GSab87SYWZeVA4zj5Om65wHaEK?pid=ImgDet&rs=1",
        name:'Toyota RAV4',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Hybrid',
        mileage:'6.1',
        rent_price:'440',
        page:4,
    },
    {
        img:"https://th.bing.com/th/id/OIP.khW3FsQQ-vVq6zEyAhN5ygHaE8?pid=ImgDet&rs=1",
        name:'BMW 3 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'8.2',
        rent_price:'350',
        page:4,
    },
    {
        img:'https://media.autoexpress.co.uk/image/private/s--cPAkU3m9--/v1563182810/autoexpress/2019/04/01_53.jpg',
        name:'VW T-Cross',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'5.3',
        rent_price:'400',
        page:4,
    },
    {
        img:'https://cdn.motor1.com/images/mgl/lNnnl/s1/cadillac-escalade-sport-edition.jpg',
        name:'Cadillac Escalade',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.7',
        rent_price:'620',
        page:4,
    },
    {
        img:'https://th.bing.com/th/id/OIP.cAzshZwI01cwuyX2YgwwtAHaE8?pid=ImgDet&rs=1',
        name:'BMW 4 Series GTI',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.6',
        rent_price:'530',
        page:4,
    },
    {
        img:'https://cdn.bmwblog.com/wp-content/uploads/2017/01/2017-BMW-4-Series-M-Sport-Coupe-25.jpg',
        name:'BMW 4 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.2',
        rent_price:'490',
        page:4,
    },
    {
        img: "https://th.bing.com/th/id/OIP.GSab87SYWZeVA4zj5Om65wHaEK?pid=ImgDet&rs=1",
        name:'Toyota RAV4',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Hybrid',
        mileage:'6.1',
        rent_price:'440',
        page:5,
    },
    {
        img:"https://th.bing.com/th/id/OIP.khW3FsQQ-vVq6zEyAhN5ygHaE8?pid=ImgDet&rs=1",
        name:'BMW 3 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'8.2',
        rent_price:'350',
        page:5,
    },
    {
        img:'https://media.autoexpress.co.uk/image/private/s--cPAkU3m9--/v1563182810/autoexpress/2019/04/01_53.jpg',
        name:'VW T-Cross',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'5.3',
        rent_price:'400',
        page:5,
    },
    {
        img:'https://cdn.motor1.com/images/mgl/lNnnl/s1/cadillac-escalade-sport-edition.jpg',
        name:'Cadillac Escalade',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.7',
        rent_price:'620',
        page:5,
    },
    {
        img:'https://th.bing.com/th/id/OIP.cAzshZwI01cwuyX2YgwwtAHaE8?pid=ImgDet&rs=1',
        name:'BMW 4 Series GTI',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.6',
        rent_price:'530',
        page:5,
    },
    {
        img:'https://cdn.bmwblog.com/wp-content/uploads/2017/01/2017-BMW-4-Series-M-Sport-Coupe-25.jpg',
        name:'BMW 4 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.2',
        rent_price:'490',
        page:5,
    },
    {
        img: "https://th.bing.com/th/id/OIP.GSab87SYWZeVA4zj5Om65wHaEK?pid=ImgDet&rs=1",
        name:'Toyota RAV4',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Hybrid',
        mileage:'6.1',
        rent_price:'440',
        page:6,
    },
    {
        img:"https://th.bing.com/th/id/OIP.khW3FsQQ-vVq6zEyAhN5ygHaE8?pid=ImgDet&rs=1",
        name:'BMW 3 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'8.2',
        rent_price:'350',
        page:6,
    },
    {
        img:'https://media.autoexpress.co.uk/image/private/s--cPAkU3m9--/v1563182810/autoexpress/2019/04/01_53.jpg',
        name:'VW T-Cross',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'5.3',
        rent_price:'400',
        page:6,
    },
    {
        img:'https://cdn.motor1.com/images/mgl/lNnnl/s1/cadillac-escalade-sport-edition.jpg',
        name:'Cadillac Escalade',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.7',
        rent_price:'620',
        page:6,
    },
    {
        img:'https://th.bing.com/th/id/OIP.cAzshZwI01cwuyX2YgwwtAHaE8?pid=ImgDet&rs=1',
        name:'BMW 4 Series GTI',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.6',
        rent_price:'530',
        page:6,
    },
    {
        img:'https://cdn.bmwblog.com/wp-content/uploads/2017/01/2017-BMW-4-Series-M-Sport-Coupe-25.jpg',
        name:'BMW 4 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.2',
        rent_price:'490',
        page:6,
    },
    {
        img: "https://th.bing.com/th/id/OIP.GSab87SYWZeVA4zj5Om65wHaEK?pid=ImgDet&rs=1",
        name:'Toyota RAV4',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Hybrid',
        mileage:'6.1',
        rent_price:'440',
        page:7,
    },
    {
        img:"https://th.bing.com/th/id/OIP.khW3FsQQ-vVq6zEyAhN5ygHaE8?pid=ImgDet&rs=1",
        name:'BMW 3 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'8.2',
        rent_price:'350',
        page:7,
    },
    {
        img:'https://media.autoexpress.co.uk/image/private/s--cPAkU3m9--/v1563182810/autoexpress/2019/04/01_53.jpg',
        name:'VW T-Cross',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'5.3',
        rent_price:'400',
        page:7,
    },
    {
        img:'https://cdn.motor1.com/images/mgl/lNnnl/s1/cadillac-escalade-sport-edition.jpg',
        name:'Cadillac Escalade',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.7',
        rent_price:'620',
        page:7,
    },
    {
        img:'https://th.bing.com/th/id/OIP.cAzshZwI01cwuyX2YgwwtAHaE8?pid=ImgDet&rs=1',
        name:'BMW 4 Series GTI',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.6',
        rent_price:'530',
        page:7,
    },
    {
        img:'https://cdn.bmwblog.com/wp-content/uploads/2017/01/2017-BMW-4-Series-M-Sport-Coupe-25.jpg',
        name:'BMW 4 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.2',
        rent_price:'490',
        page:7,
    },
    {
        img: "https://th.bing.com/th/id/OIP.GSab87SYWZeVA4zj5Om65wHaEK?pid=ImgDet&rs=1",
        name:'Toyota RAV4',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Hybrid',
        mileage:'6.1',
        rent_price:'440',
        page:8,
    },
    {
        img:"https://th.bing.com/th/id/OIP.khW3FsQQ-vVq6zEyAhN5ygHaE8?pid=ImgDet&rs=1",
        name:'BMW 3 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'8.2',
        rent_price:'350',
        page:8,
    },
    {
        img:'https://media.autoexpress.co.uk/image/private/s--cPAkU3m9--/v1563182810/autoexpress/2019/04/01_53.jpg',
        name:'VW T-Cross',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'5.3',
        rent_price:'400',
        page:8,
    },
    {
        img:'https://cdn.motor1.com/images/mgl/lNnnl/s1/cadillac-escalade-sport-edition.jpg',
        name:'Cadillac Escalade',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.7',
        rent_price:'620',
        page:8,
    },
    {
        img:'https://th.bing.com/th/id/OIP.cAzshZwI01cwuyX2YgwwtAHaE8?pid=ImgDet&rs=1',
        name:'BMW 4 Series GTI',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.6',
        rent_price:'530',
        page:8,
    },
    {
        img:'https://cdn.bmwblog.com/wp-content/uploads/2017/01/2017-BMW-4-Series-M-Sport-Coupe-25.jpg',
        name:'BMW 4 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.2',
        rent_price:'490',
        page:8,
    },
    {
        img: "https://th.bing.com/th/id/OIP.GSab87SYWZeVA4zj5Om65wHaEK?pid=ImgDet&rs=1",
        name:'Toyota RAV4',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Hybrid',
        mileage:'6.1',
        rent_price:'440',
        page:9,
    },
    {
        img:"https://th.bing.com/th/id/OIP.khW3FsQQ-vVq6zEyAhN5ygHaE8?pid=ImgDet&rs=1",
        name:'BMW 3 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'8.2',
        rent_price:'350',
        page:9,
    },
    {
        img:'https://media.autoexpress.co.uk/image/private/s--cPAkU3m9--/v1563182810/autoexpress/2019/04/01_53.jpg',
        name:'VW T-Cross',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'5.3',
        rent_price:'400',
        page:9,
    },
    {
        img:'https://cdn.motor1.com/images/mgl/lNnnl/s1/cadillac-escalade-sport-edition.jpg',
        name:'Cadillac Escalade',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.7',
        rent_price:'620',
        page:9,
    },
    {
        img:'https://th.bing.com/th/id/OIP.cAzshZwI01cwuyX2YgwwtAHaE8?pid=ImgDet&rs=1',
        name:'BMW 4 Series GTI',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.6',
        rent_price:'530',
        page:9,
    },
    {
        img:'https://cdn.bmwblog.com/wp-content/uploads/2017/01/2017-BMW-4-Series-M-Sport-Coupe-25.jpg',
        name:'BMW 4 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.2',
        rent_price:'490',
        page:9,
    },
    {
        img: "https://th.bing.com/th/id/OIP.GSab87SYWZeVA4zj5Om65wHaEK?pid=ImgDet&rs=1",
        name:'Toyota RAV4',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Hybrid',
        mileage:'6.1',
        rent_price:'440',
        page:10,
    },
    {
        img:"https://th.bing.com/th/id/OIP.khW3FsQQ-vVq6zEyAhN5ygHaE8?pid=ImgDet&rs=1",
        name:'BMW 3 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'8.2',
        rent_price:'350',
        page:10,
    },
    {
        img:'https://media.autoexpress.co.uk/image/private/s--cPAkU3m9--/v1563182810/autoexpress/2019/04/01_53.jpg',
        name:'VW T-Cross',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'5.3',
        rent_price:'400',
        page:10,
    },
    {
        img:'https://cdn.motor1.com/images/mgl/lNnnl/s1/cadillac-escalade-sport-edition.jpg',
        name:'Cadillac Escalade',
        year:'2020',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.7',
        rent_price:'620',
        page:10,
    },
    {
        img:'https://th.bing.com/th/id/OIP.cAzshZwI01cwuyX2YgwwtAHaE8?pid=ImgDet&rs=1',
        name:'BMW 4 Series GTI',
        year:'2021',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.6',
        rent_price:'530',
        page:10,
    },
    {
        img:'https://cdn.bmwblog.com/wp-content/uploads/2017/01/2017-BMW-4-Series-M-Sport-Coupe-25.jpg',
        name:'BMW 4 Series',
        year:'2019',
        seating:'4',
        transmission:'Automatic',
        fuel_type:'Gasoline',
        mileage:'7.2',
        rent_price:'490',
        page:10,
    },
]
}
